DROP TABLE IF EXISTS Query_Log CASCADE;
DROP TABLE IF EXISTS Detalle_Orden CASCADE;
DROP TABLE IF EXISTS Producto CASCADE;
DROP TABLE IF EXISTS Orden CASCADE;
DROP TABLE IF EXISTS Cliente CASCADE;
DROP TABLE IF EXISTS Categoria CASCADE;
DROP TABLE IF EXISTS Zonas CASCADE;
DROP TABLE IF EXISTS Repartidor CASCADE;

DROP EXTENSION IF EXISTS postgis CASCADE